#!/bin/bash
echo "Compiling..."
gcc -g -Og -std=c++11 pythia8root.cpp -I`${ROOTSYS}/bin/root-config --incdir` `${ROOTSYS}/bin/root-config --libs` -L/expsoft/pythia8/lib -lpythia8 -I/expsoft/pythia8/include/Pythia8 -I/expsoft/pythia8/include -lstdc++ -lm -lEG -lEGPythia8 -o pythia8root
if [[ "$?" == "0" ]]; then
	echo "Compliation completed successfully"
	echo "Running GEN stage with Pythia"
	sleep 5
	for i in `seq 0 7`;do 
		#"cp" -f ../jpsiInclusive.cmnd jpsiInclusive${i}.cmnd
		# generate a random seed between 1 and 900000000
		#SEED=$(expr $RANDOM \* $(echo $RANDOM / 1.193 | bc) + 1)
		#echo "Random:seed = $SEED" >> jpsiInclusive${i}.cmnd
		./pythia8root jpsiInclusive-pt120.cmnd /data/$USER/jpsiInclusive${i}-gen8-pt120.root &
		sleep 2
	done

	wait

	if [[ "$?" == "0" ]]; then
		echo "GEN stage completed successfully"
		hadd -f /data/$USER/jpsiInclusive-gen8K-pt120.root /data/$USER/jpsiInclusive?-gen8-pt120.root
		if [[ "$?" == "0" ]]; then
		    echo "run \`root -l /data/$USER/jpsiInclusive-gen8K-pt120.root' to view results"
		    rm -f /data/$USER/jpsiInclusive?-gen8-pt120.root
		else
		    echo "hadd stage failed"
		fi
	else
		echo "GEN stage failed"
	fi
else
	echo "Compilation failed"
fi
