#!/bin/bash
echo "Compiling..."
gcc -g -Og -std=c++11 pythia8root.cpp -I`${ROOTSYS}/bin/root-config --incdir` `${ROOTSYS}/bin/root-config --libs` -L/expsoft/pythia8/lib -lpythia8 -I/expsoft/pythia8/include/Pythia8 -I/expsoft/pythia8/include -lstdc++ -lm -lEG -lEGPythia8 -I`/expsoft/fastjet-3.3.0-cms/bin/fastjet-config --cxxflags --libs --plugins` -o pythia8root
if [[ "$?" == "0" ]]; then
	echo "Compliation completed successfully"
	echo "Running GEN stage with Pythia"
	sleep 5
	./pythia8root ../jet.cmnd /data/$USER/jet-gen2K-pt60.root
	if [[ "$?" == "0" ]]; then
		echo "GEN stage completed successfully"
		echo "run \`root -l /data/$USER/jet-gen2K-pt60.root' to view results"
	else
		echo "GEN stage failed"
	fi
else
	echo "Compilation failed"
fi
